### ISSUE TITLE
Graph gets distorted for 2-3 min every time after 30mins of display.

### ISSUE THREAD

**Issue by sachintulla** [gpbl/SwiftChart#17]
Graph gets distorted for 2-3 min every time after 30mins of display where the graph is updated for every 5secs.

**Comment by gpbl** [comment]
@sachintulla could you attach a screenshot? Thanks!

**Comment by sachintulla** [comment]
Hi Team, please find the attachment.


Thank you,
Sachin Tulla.

> On Jan 14, 2016, at 4:08 PM, Giampaolo Bellavite <notifications@github.com> wrote:
> 
> @sachintulla could you attach a screenshot? Thanks!
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
If you have received this email in error please notify the sender and then 
delete it immediately. This message contains confidential information and 
is intended only for the individual(s) named. If you are not the named 
addressee you should not disseminate, distribute or copy this email.

**Comment by gpbl** [comment]
Please send the attachment from github 😅

**Comment by gpbl** [comment]
Closing because lack of activity – please reopen if needed, thanks!
