### ISSUE TITLE
xLabel - Time

### ISSUE THREAD

**Issue by Dem909** [gpbl/SwiftChart#19]
how to display time in a xLabel? For example, I have a value and time (in the format HH: mm), how can I display the time at the bottom (eg every 4 hours), and draw a graph based on my time-value?
PS. Sorry for my English, I use google.translit

**Comment by gpbl** [comment]
Hi @Dem909, you should provide an array of labels to `xLabels`. See [this example](https://github.com/gpbl/SwiftChart/blob/master/Example/SwiftChart/StockChartViewController.swift).

**Comment by Dem909** [comment]
I looked, but somehow I can not.

var labelsAsString: Array<String> = ["00.00", "4.00", "8.00", "12.00", "16.00", "20.00", "24.00"]
        chart.xLabelsFormatter = { (labelIndex: Int, labelValue: Float) -> String in
            return labelsAsString[labelIndex]
        }

chart.xLabels = [0, 1, 2, 3, 4, 5, 6]

for r in records as! [Diary] {

             var data: Array<Float> = []

            for(var i=0;i<=100;i++){
                var active_hours = NSString(string: insulin.valueForKey("active_hours") as! String).doubleValue * 60.0 * 60.0
                var active = (active_hours / 100) * Double(i)
                var value = r.bolusInsulin?.doubleValue
                var active_value = value! - (((r.bolusInsulin?.doubleValue)! / 100) * d[i])
                data.append(Float(active_value))
            }
            
            let series = ChartSeries(data)
            chart.addSeries(series)
            
        }



In the loop we add the elements in an array (which is added to the series), but the problem is that the schedule begins with UIVIew, not since the time when we must begin to build and time (00:00, 4:00, and so on. d.) somehow stick together in a heap

**Comment by gpbl** [comment]
@Dem909 I'm not sure I understand where is your problem – would you mind to attach a screenshot? 

Also, it would help to have the output of `print(data)`.

**Comment by gpbl** [comment]
Closing because lack of activity – please reopen if needed, thanks!
