### ISSUE TITLE
series not showing up in the view

### ISSUE THREAD

**Issue by r-shayestehpour** [gpbl/SwiftChart#21]
First of all, thanks for your cool repo!
I have this app that gets some data from server using Alamofire, and I want to show the data on a chart using your library, I have the following code:

```swift

    @IBOutlet weak var chart: Chart!
    
    // MARK: - view controller life cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        /*let series = ChartSeries([0, 6, 2, 8, 4, 7, 3, 10, 8])
        series.color = ChartColors.greenColor()
        chart.addSeries(series)*/
        self.getPriceList()
    }
    
    // MARK: - ui code

    func updateChart() {
        
        /*var data : [Float] = []
        for (_, node) in self.priceList {
            print(node)
            data.append(node["y"].floatValue)
        }*/
        dispatch_async(dispatch_get_main_queue(), { () -> Void in
            /*let serie = ChartSeries(data)
            serie.color = ChartColors.blueColor()
            self.chart.addSeries(serie)*/
            let series = ChartSeries([3, 5, 2, 2, 4, 7, 3, 10, 8])
            series.color = ChartColors.blueColor()
            self.chart.addSeries(series)
        })
    }
    
    // MARK: - api calls, parsing and processing responses
    
    func getPriceList() {
        let requestDictionary = [
            "action": "GetInstruemntChart",
            "sessionID": Configurations.sessionID,
            "versionCode": "\(Configurations.versionCode)",
            "duration": "3"
        ]
        
        Alamofire.upload(
            .POST,
            Configurations.baseURL,
            multipartFormData: { multipartFormData in
                Networking.multipartFormDataBody(multipartFormData, dictionary: requestDictionary)
            },
            encodingCompletion: { encodingResult in
                switch encodingResult {
                case .Success(let upload, _, _):
                    upload.responseData() {response in
                        if let data = response.result.value {
                            debugPrint("got price list")
                            self.parsePriceListResponse(data)
                        }
                    }
                case .Failure(let encodingError):
                    print(encodingError)
                }
            }
        )
    }
    
    func parsePriceListResponse(data: NSData) {
        let json = JSON(data: data)
        
        self.priceList = json["priceList"]
        self.updateChart()
    }
```

I added the view in IB, but after getting the response, the chart series is not shown on the view(only the vertical line indicator for the chart appears and moves with touch events). As you can see I commented the code which tries to use the server data to draw the chart and added a simple code from your example and still nothing shows up.

ps: in my code, in `viewDidLoad` method, I added a simple series to check if the chart works at all and that one is shown, but the one in `updateChart` is not.

this is the chart view as i described.

<img width="372" alt="screen shot 2016-02-14 at 1 16 49 am" src="https://cloud.githubusercontent.com/assets/3146175/13030238/c4b42260-d2b8-11e5-96fa-6a065142b651.png">

is there something I'm doing wrong?

**Comment by gpbl** [comment]
Hi @r-shayestehpour, thanks! 

It's not possible yet to update the chart after you have already initialized it. Instead, initialize (or re-initialize) a new chart once you get the response from Alamofire: it should work! In this case I don't think you can use IB.

**Comment by r-shayestehpour** [comment]
thanks. :)

**Comment by r-shayestehpour** [comment]
in the instructions, you say to initialize the chart using `Chart(frame:)` but it seems like there is no such initializer:


<img width="1280" alt="screen shot 2016-02-14 at 11 29 56 pm" src="https://cloud.githubusercontent.com/assets/3146175/13036077/22ed0404-d373-11e5-90f6-54730736a8e9.png">

**Comment by gpbl** [comment]
You are right, it was missing the public initializer. You can find it in the last release :) https://github.com/gpbl/SwiftChart/releases/latest

it should appear on cocoapods soon.

**Comment by deepakdewani123** [comment]
how do I add a chart programmatically in Swift? can you please give the complete code?

**Comment by gpbl** [comment]
@deepakdewani123 It's all explained in the readme 😄 Check the Examples directory as well to see how to use the library

**Comment by deepakdewani123** [comment]
Thanks for your reply. I tried everything given in the readme file but I couldn't get it working. Also, the example only shows how to do it using IB and not with code. 

 var chart = Chart()
        var myview = UIView(frame: CGRect(x: 50, y: 200, width: 200, height: 200))
        chart = Chart(frame: CGRect(x: 50, y: 200, width: 200, height: 200))
        chart.backgroundColor = UIColor.redColor()
        chart.center = view.center
        let series = ChartSeries([1,2,3,4,5])
        series.color = UIColor.orangeColor()
        series.area = true
        
        chart.lineWidth = 1
        chart.addSeries(series)
        
        myview.addSubview(chart)
        view.addSubview(myview)

This is the code that I've written.

**Comment by deepakdewani123** [comment]
I'm having the same issue as @r-shayestehpour

**Comment by gpbl** [comment]
@deepakdewani123 Which problem do you mean? Does the chart appear ? Are you initializing the chart in `viewDidLoad`?

**Comment by deepakdewani123** [comment]
The problem that I'm getting some float values using Alamofire but after getting the values I'm not able to draw the chart. The chart doesn't appear. Yes, I'm initializing the chart in viewDidLoad.

**Comment by deepakdewani123** [comment]
could you tell me how do I get it working without using IB? I want to get the chart drawn on a UIView in a UIViewController.

**Comment by gpbl** [comment]
@deepakdewani123 There's not so much to add to what's in the README :) 

The IB just initializes the views in the same way - so my guess is that your subview is not initialized, sized or placed correctly. 

Make sure the views are correctly initialized in the main view - e.g. by inspecting the views layers, or by initializing a simple UIView with a colored background instead of the chart. Also, try to not to nest the chart in a subview for better debugging.

**Comment by deepakdewani123** [comment]
okay. So if I'm adding the chart through code, do I need to assign the Chart class to the UIView in the IB and then make the @IBOutlet or without assigning the class?

**Comment by deepakdewani123** [comment]
Well, sometimes something is right in front of you but you can't recognize it. I got it working. Thanks for such an amazing library and for your help.

**Comment by gpbl** [comment]
@deepakdewani123 Glad you solved it! Where was the issue?

**Comment by deepakdewani123** [comment]
I wasn't adding the chart as a subview of the UIView in my VC.

**Comment by deepakdewani123** [comment]
Hi!
How do I change the series value dynamically in a view?
I'm adding a series to a view but when I try to change that dynamically, it doesn't change.

**Comment by gpbl** [comment]
@deepakdewani123 please don't hijack this issue with other questions nor use the github issues as a support chat. Please check https://github.com/gpbl/SwiftChart#how-do-i-update-the-chart-series

Thanks!
