### ISSUE TITLE
Select last Chart element on right side

### ISSUE THREAD

**Issue by kevinlieser** [gpbl/SwiftChart#23]
How can I select the last chart dot on the right side with finger event? I have tried to modify the method and added half width of the space between the lines to variable x before it gets sent to the calculating method. This just gives the ability to recognize the new returning index in the middle of two points not "on line for the whole left part".

But any idea how to get the last object on the right side selected after middle position between last and previous line?

**Comment by kevinlieser** [comment]
Got this workaround:

`func handleTouchEvents(touches: NSSet!, event: UIEvent!) {
		let point: AnyObject! = touches.anyObject()
        let left = point.locationInView(self).x
		let x = valueFromPointAtX(left)
		
		var lastLinesTouch: Int = 0
		if(self.series.count != 0) {
			if(left > CGFloat(drawingWidth - ((drawingWidth / CGFloat(self.series[0].data.count - 1)) / 2))) {
				lastLinesTouch = 1
			}
		}

        if left < 0 || left > drawingWidth {
            // Remove highlight line at the end of the touch event
            if let shapeLayer = highlightShapeLayer {
                shapeLayer.path = nil
            }
            delegate?.didFinishTouchingChart(self)
            return
        }

        drawHighlightLineFromLeftPosition(left)

        if delegate == nil {
            return
        }

        var indexes: Array<Int?> = []

        for series in self.series {
            var index: Int? = nil
            let xValues = series.data.map({ (point: ChartPoint) -> Float in
                return point.x
			})
			
            let closest = Chart.findClosestInValues(xValues, forValue: x)
            if closest.lowestIndex != nil && closest.highestIndex != nil {
				// Consider valid only values on the right
				index = closest.lowestIndex
            }
			if(index == nil) {
				if(lastLinesTouch == 1) { index = self.series[0].data.count - 1 }
			}
            indexes.append(index)
        }

        delegate!.didTouchChart(self, indexes: indexes, x: x, left: left)

    }`

`private class func findClosestInValues(values: Array<Float>, forValue value: Float) -> (lowestValue: Float?, highestValue: Float?, lowestIndex: Int?, highestIndex: Int?) {
        var lowestValue: Float?, highestValue: Float?, lowestIndex: Int?, highestIndex: Int?

		let valueAdded = value + 0.5
		
        values.enumerate().forEach { (i, currentValue) in
			if currentValue <= valueAdded && (lowestValue == nil || lowestValue! < currentValue) {
                lowestValue = currentValue
                lowestIndex = i
            }
            if currentValue >= valueAdded && (highestValue == nil || highestValue! > currentValue) {
                highestValue = currentValue
                highestIndex = i
            }

        }
        return (lowestValue: lowestValue, highestValue: highestValue, lowestIndex: lowestIndex, highestIndex: highestIndex)
    }`

**Comment by gpbl** [comment]
@kevinlieser Hi @kevinlieser would you mind to attach a gif showing the behavior you needed? I'm not sure I understand 😅

**Comment by kevinlieser** [comment]
Just check the code changes above ;-)

**Comment by gpbl** [comment]
@kevinlieser i think I can close this. Please reopen if needed, thanks!
