### ISSUE TITLE
Bug: red lines and area with positive values

### ISSUE THREAD

**Issue by aalfath** [gpbl/SwiftChart#26]
Hello,

Thanks for creating this library!

I'm not sure if this one is a bug or not, but I tried to create a chart from the example chart with y-min and y-max and I'm not sure if the chart generates correctly.

![image](https://cloud.githubusercontent.com/assets/7084258/16617633/0e8381d2-4385-11e6-8e0a-5c0cec078333.png)

There are some red lines and area with certainly positive values in its data.
Is this a normal behavior?

I tried to check the value of the series and it does indeed positive (more than 0)

Any help would be appreciated!

**Comment by aalfath** [comment]
Hi @gpbl, kindly used below data:
`let data: Array<Float> = [-0.0,  -2.70548,  -2.63699,  3.09075,  -3.05268, -0.0, 4.44349, 1.0, -0.0, -1.30397, -0.0, -0.0, 1.64384, -3.17637, 4.92295, -1.89212, -3.44178, -4.09326, -0.0, 2.06336, -2.5, 2.74829, -4.8532, 1.4726, -2.32021, -0.0, -0.0, -4.375, 4.10663, -0.821326, -1.77233, 1.73801]`

Also, I can confirm that the bug would still appear even when minY and maxY is not defined. I have edited the title to avoid misunderstanding

**Comment by gpbl** [comment]
I can replicate this behavior even with

```swift
let data: Array<Float> = [0, -2, -2, 3, -3, 4, 1, 0, -1]
```

It seems the zero is giving problems when calculating positive/negative lines. Fix is coming, thanks for finding it out.

(note to myself: [this line](https://github.com/gpbl/SwiftChart/blob/master/Source/Chart.swift#L774) should check `<= 0` not just `< 0`.)

**Comment by gpbl** [comment]
You can download the fixed release from https://github.com/gpbl/SwiftChart/releases/tag/v0.2.2, releasing on cocoapod soon once I remember how it works 📦 😛

**Comment by aalfath** [comment]
Thank you for the quick fix, much appreciated! 😃 👍

**Comment by gpbl** [comment]
You are welcome! please reopen if needed (couldn't test the fix heavily).
