### ISSUE TITLE
Partial graph

### ISSUE THREAD

**Issue by michaelschwinges** [gpbl/SwiftChart#28]
Hi,

I am drawing a line graph of price movements during the day. The thing is, that if I create a graph, for example from 9:00 AM until 11:00 AM, then the graph is only two hours wide. I really would want to draw the graph to be as wide as 9:00 AM to 5:00 PM and the line on the graph gets wider during as the day progresses.

Is there an enhancement that will allow me to draw a full scale with labels but only have data points for a portion of the Y values? I've attached a mockup - a picture speaks a thousand words :-)

![eg](https://cloud.githubusercontent.com/assets/11598368/17461510/2bec7ba2-5c8f-11e6-93d5-f50971e6a77c.png)

**Comment by gpbl** [comment]
Hi @michaelschwinges!

Yes this is actually a very similar case for which i created this library. E.g.

```swift

// Simple chart
let data = [(x: 0.0, y: 0), (x: 3, y: 2.5), (x: 4, y: 2), (x: 7, y: 3), (x: 9, y: 2.5)]
let series = ChartSeries(data: data)
series.area = true
chart.xLabels = [0, 3, 6, 9, 12, 15, 18, 21, 24]
chart.xLabelsFormatter = { String(Int(round($1))) + "h" }
series.color = ChartColors.greenColor()
chart.addSeries(series)
```

this will render the following:

<img width="438" alt="screen shot 2016-08-07 at 11 32 48" src="https://cloud.githubusercontent.com/assets/120693/17461596/bab98cf0-5c92-11e6-8ac5-9a020c6fabc0.png">

I see now that the `xLabels` prop is missing from the docs...

**Comment by michaelschwinges** [comment]
Wow cool, thank you for the quick response and the example!
