### ISSUE TITLE
Swift 3 Compatibility

### ISSUE THREAD

**Issue by Bonney** [gpbl/SwiftChart#29]
Hey, so, I've never actually contributed to a project before, but I downloaded this earlier hoping to use it in my app (Swift 3/iOS 10). Obviously with all the syntax changes between Swift 2 & 3 it didn't work automatically, so I went ahead and updated Chart.swift with the changes to CGPathAddLineToPoint, CGPathMoveToPoint and the like to bring it up to compatibility with Swift 3.

As I said, I've never contributed to a project before. Just started using git about a month ago, in fact. Not even sure what the proper way to go about submitting the changes back for approval is, but I'd be more than happy to provide the updated file!

**Comment by souvik1997** [comment]
I'm working on a Swift 3 version. 

https://github.com/souvik1997/SwiftChart

**Comment by souvik1997** [comment]
I made a PR a few minutes ago. You could try merging your code with mine (if it's different)

https://github.com/gpbl/SwiftChart/pull/30

**Comment by gpbl** [comment]
Thanks a lot and congrats for your first pull request 🙌

I'd like to test the changes on iOS 10 before merging, please have some patience 😀

**Comment by emonfil87** [comment]
It is long to have the compatible version swift 3

**Comment by Natelegreat1** [comment]
@souvik1997 Have you tried your code in Xcode 8? I'm getting 81 errors... not such simple ones either!

**Comment by souvik1997** [comment]
What kind of errors are you getting? I'm also using Xcode 8 and I don't see anything wrong.

**Comment by gpbl** [comment]
Hi all! Support for Swift 3 is available in v0.3.0, please check the [changelog](https://github.com/gpbl/SwiftChart/releases) for breaking changes, thanks!
