### ISSUE TITLE
Display the last label to the x axis

### ISSUE THREAD

**Issue by Cyphontin** [gpbl/SwiftChart#37]
The last char (here "D") is not displayed.

var labelsAsString: Array<String> = ["L", "M", "M", "J", "V", "S", "D"]
        stats.xLabelsFormatter = { (labelIndex: Int, labelValue: Float) -> String in
            return labelsAsString[labelIndex]
        }

Even if we use xLabelsTextAlignment = .left

![capture d ecran 2016-10-16 a 14 24 28](https://cloud.githubusercontent.com/assets/22193771/19417421/d7b83d46-93ac-11e6-9370-90fee7e7603f.png)

![capture d ecran 2](https://cloud.githubusercontent.com/assets/22193771/19417451/bb230e62-93ad-11e6-96c9-937eaaef931b.png)

**Comment by theduman** [comment]
if you create one more data without adding a xlabel for it.it shows the last label that you wanted.Your last xlabel still there but it needs one more chart data to shown.Its a bug i think.

**Comment by gpbl** [comment]
Hi people, yes this is a wanted behaviour, I still need to understand what's the best thing to do here. Where should the missing label go? What are your expectations?

**Comment by theduman** [comment]
Hi gpbl.Thanks for your respond.According to my project, i got (n) number data and (n) number xlabel for that data.xLabel is created right after the my data appeared in my chart.But when my last data appeared in chart view,chart ends.If there is a way to expand chart view without data so i can fit my last xlabel?Thanks for your attention.

**Comment by Cyphontin** [comment]
I think it will be better if we can see all labels even if you need to add a margin. Thank you.

**Comment by gpbl** [comment]
@Cyphontin so in your first case how should it look the chart? Where would you put the `D`?

**Comment by Cyphontin** [comment]
Is something like this possible ?
![chart](https://cloud.githubusercontent.com/assets/22193771/19470643/969b5724-9520-11e6-9a33-a69441c2e5e3.png)

**Comment by gpbl** [comment]
Yup this is something we could support, we should just remove [this line]. I need however to double check how does it works as the the labels would span outside the chart area.

**Comment by rjong** [comment]
+1

**Comment by scinfu** [comment]
+1

**Comment by gpbl** [comment]
I've published v0.5.0 with a new option `xLabelsSkipLast`. Set it to `false` if you want to display the last label as well. 

However, the label will overflow the chart width (this is the reason it is set to false as default).  Since this seems a common feature request, please someone send a PR to try solving this issue 🙏🏽

**Comment by Cyphontin** [comment]
Thank you
