### ISSUE TITLE
Swift Compiler Error (Xcode 8.1)

### ISSUE THREAD

**Issue by 9SL9** [gpbl/SwiftChart#42]
After upgrading to Xcode 8.1 I'm getting the error below in swift.chart

<img width="756" alt="error" src="https://cloud.githubusercontent.com/assets/5746558/19833375/b1e0c2e2-9e82-11e6-9659-2977e0c4f528.png">

**Comment by michaelschwinges** [comment]
Same happened to me. I got past it as follows:

```
// per http://stackoverflow.com/questions/39933924/subtraction-of-cgfloats-ambiguity-error-swift-3
// a workaround is to cast the first or the second variable to a non-optional
        
if left < 0 || left > (drawingWidth as CGFloat) {
```

**Comment by gpbl** [comment]
Thanks for the report!

**Comment by 9SL9** [comment]
Thanks for the update to 0.4 - any idea when this will make it into Cocoapods?

**Comment by gpbl** [comment]
I'm still on limited connection until this weekend, I hope for this sunday 👍

**Comment by 9SL9** [comment]
I'll log an issue for your limited connection if you don't make the deadline :)

**Comment by gpbl** [comment]
:D talk with @VodafoneGlobalServices for not helping against the digital divide in Italy 👎

**Comment by 9SL9** [comment]
JIT :)

**Comment by gpbl** [comment]
I've finally published the pod 🎉
