### ISSUE TITLE
Feature request: custom threshold for positive/negative data display

### ISSUE THREAD

**Issue by 9SL9** [gpbl/SwiftChart#43]
I'm wondering if it's possible to set a custom threshold for positive/negative display of data? For example, I'd like to set a value of 5 where a value between 0-5 is red and 5-10 is blue.

It appears this functionality is only available if the value is below zero.

Thanks for your consideration.

**Comment by gpbl** [comment]
Sure it would be possible, if I understand right you need something like https://github.com/gpbl/SwiftChart/issues/34 @Cyphontin requested.

or better, what would you expect for values below 0 and above 10 in your example?

**Comment by 9SL9** [comment]
Exactly the same request. I'll give it a shot with a pull request.

**Comment by Cyphontin** [comment]
I wanted to make a PR but did not work :o/

**Comment by 9SL9** [comment]
I'll be in same boat...need to figure it out

**Comment by algrid** [comment]
Hi! I added my PR for this feature. Does it look like what you've been asking for?

**Comment by Cyphontin** [comment]
It's exactly what I asked.  Thank a lot.

**Comment by gpbl** [comment]
Closed by #45. Releasing soon on cocoapods. Thanks @algrid

**Comment by gpbl** [comment]
Uh I'll release on cocoapods the next days as I'm on a limited connection and cocooapods seems to want to download the entire github 😅
