### ISSUE TITLE
Why only can set the chart in "ViewDidLoad"

### ISSUE THREAD

**Issue by WebberLai** [gpbl/SwiftChart#52]
Hi , I got strange issue , why only can init the chart in "ViewDidLoad" ???

I was try to add an IBAction for remove series or update the chart .

But nothing happen ???

Does anyone has same problem like me ???

**Comment by Hemen** [comment]
I have having the same issue.

I am fetching stock info from the API and then try to load the fourth chart and chart is not generating the lines.

Let me know if anyone have any idea.

**Comment by gpbl** [comment]
Hi people, the chart must be initialized when the view is loaded because it needs to know the horizontal space. Try to call `chart.setNeedsDisplay()` to redraw the chart.

**Comment by WebberLai** [comment]
Sorry , I was trying to add comment , but wrong press the button 
.setNeedsDisplay() can solve the problem

**Comment by Hemen** [comment]
It is resolved now! Thank you so much.
