### ISSUE TITLE
didFinishTouchingChart not called

### ISSUE THREAD

**Issue by Sweeper777** [gpbl/SwiftChart#53]
Here's my code to add a label that shows the value of the chart when the user touches the chart.

    @IBOutlet var chart: Chart!
    @IBOutlet var label: UILabel!
    @IBOutlet var labelLeadingMarginConstraint: NSLayoutConstraint!
    
    override func viewDidLoad() {
        label.isHidden = true
        let labels = ["A", "B", "C", "D", "E", "F", "G", "H", ""]
        let chartSeries = ChartSeries([10, 5, 7, 10, 3, 6, 4, 7])
        chartSeries.area = true
        chart.add(chartSeries)
        chart.xLabelsFormatter = { index, value in return labels[index] }
        chart.xLabels = Array(0...8).map { Float($0) }
        let series = chart.series.first!
        let max = ceil(series.data.map { $0.y }.max()!)
        chart.yLabels = Array(stride(from: 0, through: max, by: 1))
        chart.delegate = self
    }
    
    func didTouchChart(_ chart: Chart, indexes: Array<Int?>, x: Float, left: CGFloat) {
        
        if let value = chart.valueForSeries(0, atIndex: indexes[0]) {
            label.isHidden = false
            let labelLeadingMarginInitialConstant = CGFloat(0)
            let numberFormatter = NumberFormatter()
            numberFormatter.minimumFractionDigits = 2
            numberFormatter.maximumFractionDigits = 2
            label.text = numberFormatter.string(from: NSNumber(value: value))
            
            // Align the label to the touch left position, centered
            var constant = labelLeadingMarginInitialConstant + left - (label.frame.width / 2)
            
            // Avoid placing the label on the left of the chart
            if constant < labelLeadingMarginInitialConstant {
                constant = labelLeadingMarginInitialConstant
            }
            
            // Avoid placing the label on the right of the chart
            let rightMargin = chart.frame.width - label.frame.width
            if constant > rightMargin {
                constant = rightMargin
            }
            
            labelLeadingMarginConstraint.constant = constant
            
        }
        
    }
    
    func didFinishTouchingChart(_ chart: Chart) {
        label.isHidden = true
    }

As you can see in my `didFinishTouchingChart` method, I hide the label.

When I run the app, the label is hidden at first. When I touch the chart, the label shows up. But when my finger lifts up, the label does not disppear! I put a breakpoint in `didFinishTouchingChart` and saw that the method is never called. Why does this happen? Is `didFinishTouchingChart` supposed to be called when touches ended?

**Comment by gpbl** [comment]
Maybe a dup of this? https://github.com/gpbl/SwiftChart/issues/22

**Comment by Sweeper777** [comment]
Yes it seems like it.
