### ISSUE TITLE
How to avoid chart flashing when update the series ?

### ISSUE THREAD

**Issue by WebberLai** [gpbl/SwiftChart#55]
Hi , I was trying to create a chart it updates every 1 sec

Also let the chart shift the line , like watching a realtime data stream

This is my sample code , Hope you can understand what I mean

```
timer = Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(self.getData), userInfo: nil, repeats: true)

func getData(){
                //Let the chart will shift to the left
                if someSeriaData.count > MAX_RECORD_TIME {
                    someSeriaData.remove(at: 0)
                }
                //Append new data
                let randomValue = self.genRandomValue
                self.someSeriaData.append(randomValue)
                
                let series = ChartSeries(someSeriaData)
                series.color = ChartColors.cyanColor()
                self.chart.series = [series]
                DispatchQueue.main.async {
                    self.chart.setNeedsDisplay()
                }
}
```

But it always flashing when I call self.chart.setNeedsDisplay()

Is any better way to update the chart ?

Thank you , Nice graphic kit , very easy to use

**Comment by gpbl** [comment]
@WebberLai Hi @WebberLai did you try by removing and adding the series? I remember I implemented something like that... if the series is not too big it shouldn't take too much CPU. Sure live update is something it would nice to support better :)

**Comment by WebberLai** [comment]
I will try it , update comment later .

**Comment by gpbl** [comment]
@WebberLai I'm closing this, please report back if you need.
