### ISSUE TITLE
Chart drawn with an offset in IB

### ISSUE THREAD

**Issue by Sweeper777** [gpbl/SwiftChart#56]
When I add a `Chart` to the storyboard, it looks like this:

<img width="357" alt="screen shot 2016-12-29 at 4 45 07 pm" src="https://cloud.githubusercontent.com/assets/13585047/21539946/8eb6b5f4-cde6-11e6-859b-057393741600.png">

This makes it look like that the grey area that says "Chart" is the frame of the chart. However, it isn't. When I double click on the chart, everything except the frame darkens so the frame of the chart is the brightest. The result looks like this:

<img width="373" alt="screen shot 2016-12-29 at 4 44 52 pm" src="https://cloud.githubusercontent.com/assets/13585047/21539977/d22ec10a-cde6-11e6-91b9-210d3a18b283.png">

As you can see, the grey part isn't really the frame. It's quite confusing. Can you fix that?

**Comment by Cyphontin** [comment]
I have the same

**Comment by gpbl** [comment]
Hey people how do you set the chart height? 

Think kind of problems rely pm some constraints with the IB. as the chart is just a UIView.
Try to do the same with an UIView with a filled background to understand where is the issue in your constraints.

**Comment by Sweeper777** [comment]
I added a brand new `UIView` without any constraints. The result looks like this:

<img width="388" alt="screen shot 2017-01-06 at 7 36 40 am" src="https://cloud.githubusercontent.com/assets/13585047/21710806/e4ae89b2-d3e2-11e6-95b2-7f9b96ea19b6.png">
 I think this is not caused by constraints. Can you reproduce this?

**Comment by Cyphontin** [comment]
Same problem.
