### ISSUE TITLE
How to reload chart view with new data ? 

### ISSUE THREAD

**Issue by fadylateef** [gpbl/SwiftChart#57]
First thanks for great CHARTS !! 👍 

I am getting my chart data from a JSON object online.
So, when I receive the JSON data successfully I'd like to add them to the chart view and reload it again.

**Comment by Maverick25** [comment]
in the other issue, it was mentioned you call chart.setNeedsDisplay() to refresh the chart

**Comment by gpbl** [comment]
Thanks for the follow up – I've added it on the FAQ: https://github.com/gpbl/SwiftChart#how-do-i-update-the-chart-series
