### ISSUE TITLE
White lines

### ISSUE THREAD

**Issue by narekyan** [gpbl/SwiftChart#59]
Hi !

Could you tell me how I can make this happen.
I need to make chart colourful and due to i use multiple ChartSeries
But if they are too much I see white spaces between them.

![simulator screen shot 17 feb 2017 10 56 52](https://cloud.githubusercontent.com/assets/12446012/23055598/1f88737a-f500-11e6-984d-94e87c0159b1.png)

**Comment by narekyan** [comment]
@gpbl could you check please

**Comment by gpbl** [comment]
@narekyan please try to use the `gridColor` property and set it `clearColor()`, it should because the grid.
