### ISSUE TITLE
Draw Vertical xLabels?

### ISSUE THREAD

**Issue by Sweeper777** [gpbl/SwiftChart#61]
Often I need to draw graphs that have the date as the x axis i.e. showing how a quantity changes in the course of a month. I will have 30 x values and every x label is date. Then the problem comes, the x labels are so close together that the dates can't be seen. I tried to adjust the font size and making the date format as simple as possible, but there is just not enough space to show 30 dates.

I think there should be an option to make x labels vertical, like in Numbers.app:

<img width="863" alt="2017-04-01 10 40 49" src="https://cloud.githubusercontent.com/assets/13585047/24577559/d2a882fe-16c7-11e7-8206-5b1fd903330d.png">

**Comment by gpbl** [comment]
Thanks for the suggestion. From v0.5.0 you can now use the new `xLabelsOrientation` option:

```swift
Chart.xLabelsOrientation = .vertical
```
