### ISSUE TITLE
Inner area color fill between layers

### ISSUE THREAD

**Issue by iNicson** [gpbl/SwiftChart#85]
Hi fellow developer!

I am using this swiftchart in my project , I find this is the simplest and clean chart I used in many app pages. Well now I am stuck with a graph requirement where I need to show the area fill but inside the layers. I mean inner area fill between the layers like the image attached below, Can you add support for that in the upcoming version?

![33961330-abdc9d88-e073-11e7-89c9-c6ccb3eda7f9-1](https://user-images.githubusercontent.com/120693/34640634-abbe0ba8-f2f6-11e7-9bd6-1335a05a7bd2.png)

**Comment by gpbl** [comment]
Not possible out of the box, and I'm unlikely going to implement something like this – but maybe you can stack a third custom series with the diff values (green in the screenshot) between the two.
