### ISSUE TITLE
Lock the highlight line to actual data 

### ISSUE THREAD

**Issue by cyrilzakka** [gpbl/SwiftChart#86]
First off I just wanted to say I love this charting library, it's lightweight and super easy to use.
I just have one issue with it:

- Is there a way of locking the highlight line to only scroll past actual data points in the chart rather than smoothly throughout the whole chart?

**Comment by gpbl** [comment]
Hi @cyrilzakka,

there's no way currently to do this. I believe it is possible by changing https://github.com/gpbl/SwiftChart/blob/master/Source/Chart.swift#L735. However, since we support multiple series, it may be difficult to implement.
