### ISSUE TITLE
Add support to choose a different "0" scale.

### ISSUE THREAD

**Issue by MarkLyck** [gpbl/SwiftChart#9]
I noticed there's no default support to change the height of the "0" axis.

At least from what I can see in the documentation.

It would be great if there was a way to take advantage of the "below" colours.

An example use-case is this:
![screen shot 2015-06-02 at 05 08 10](https://cloud.githubusercontent.com/assets/6841110/7932321/6c144448-08e5-11e5-8593-d599a6928201.png)

It's a stock graph, where in this case the suggested price would be the "0" axis, but another use-case could be the price you bought it at, and I'm sure many others.

Having already implemented the different colours for above and below this axis, this seems like a great addition.

Should be fairly simple. If you want a pull request, I can probably add it tomorrow?

**Comment by gpbl** [comment]
@MarkLyck FYI this has been added to [v0.4](https://github.com/gpbl/SwiftChart/releases/tag/0.4.0). Thanks for the suggestion!
