### ISSUE TITLE
UI Background Thread Error

### ISSUE THREAD

**Issue by itali43** [gpbl/SwiftChart#95]
Hello!

Thanks for a great library, it's worked wonderfully for me!

I just updated my project to Swift 4 (+ XCode 9) and I'm getting an "UI API called from background thread Group" error.

Specifically:

```
Pods/SwiftChart/Source/Chart.swift: runtime: UI API called from background thread: UIView.setNeedsDisplay() must be used from main thread only
```

I was able to silence it by unlocking the pod and adding self.setNeedsDisplay() to the 'main' thread.

```swift
open var series: [ChartSeries] = [] {
        didSet {
            DispatchQueue.main.async {
                self.setNeedsDisplay()
            }
        }
    }
```

**Comment by gpbl** [comment]
Thanks for the report. I haven't tested the library with Xcode 9 yet. Does this error prevent the app to compile or crash something?

**Comment by itali43** [comment]
It makes it so the graph doesn’t load for ~20 seconds, i had a timer refreshing the data every 2 sec and it sometimes took 5-10 refreshes before it worked. 

I read the new error message is to prevent putting ui on background threads because it can cause crashes, though in this instance, i didn’t experience any.
